### ISSUE TITLE
thrift.client.retry-same-address=true  leads to infinite loop

### ISSUE THREAD

**Issue by arhimondr** [airlift/drift#100]
In case all hosts are down, retrying the same hosts over and over again creates an infinite loop. That creates a lot of CPU pressure, as there is no delay between retrying in case of a `ConnectionFailedException`.

**Comment by arhimondr** [comment]
CC: @electrum @dain

**Comment by dain** [comment]
If we kept a count of the failed connect attempts per address, we could add a simple backoff per address.

**Comment by arhimondr** [comment]
Resolved  by https://github.com/airlift/drift/pull/101
