### ISSUE TITLE
Invocation problems about asynchronous and non-asynchronous calls

### ISSUE THREAD

**Issue by dxGuan** [airlift/drift#106]
Here is my confusion:

### Server side
I have a class :```ConcreteService``` which is  of a concrete implementation of an interface: ```HelloService``` which is annotated by ```@ThriftService```.

```java
public class ConcreteService implements HelloService {

    @Override
    public String hello(String from) {
        return String.format("Hello %s, greeting from RPC server!", from);
    }

    @Override
    public ListenableFuture<String> helloAsync(String from) {
        return MoreExecutors.newDirectExecutorService().submit(() -> {
            try {
                // Going to mock a time consuming operation
                Thread.sleep(10 * 1000);
            } catch (InterruptedException ignore) {
            }
            return String.format("Hello %s, greeting from RPC server asynchronous call !", 
                    from);
        });
    }

}
```

### Client side
I create a ```HelloService``` with ```DriftClientFactory``` without any special configuration.
```java

public class ClientTest {

    public static void main(String[] args) {
        HelloService service = new DriftClientFactory(...).create(HelloService.class).get();

        // Make an async call
        ListenableFuture<String> asyncResult = service.helloAsync("derrick");
        asyncResult.addListener(() -> {
            try {
                String result = asyncResult.get();
            } catch (Exception ignore) {
            }
        }, executor);
        
        // Make a non-async call
        String result = helloService.hello("derrick");
    }
}
```

Seems like the non-async method invocation will not be executed at the server side until the completion of the async invocation.

It looks like the server side takes the request sequentially, one by one, no matter the request is async or non-async.

### My questions

* Is it a misusage or a deliberate implementation of drift?

* If it does a misusage, how can I fix it properly?

**Comment by electrum** [comment]
This is not expected. The protocol is multiplexed, so even for a single client with a single connection, there can be multiple requests in flight at once. A couple observations about your test code:

* The annotated interface does not need to be shared between client and server. It's fine to have an async server with synchronous client or vice versa.
* The async server method is actually synchronous due to the `newDirectExecutorService()`. The code is equivalent to
```java
public ListenableFuture<String> helloAsync(String from) {
    Thread.sleep(10 * 1000);
    return Futures.immediateFuture("some result");
}
```
I'll write a test case for this later to confirm (thought we had one but couldn't find it).

**Comment by dxGuan** [comment]
@electrum Cool, I have already modified the code according to your reply and everything just goes smoothly. 
I think the devil is all about using the ```MoreExecutors.newDirectExecutorService()``` improperly where I should use ```MoreExecutors.listeningDecorator(ExecutorService)``` to make tasks go asynchronously.

Thx pal.
