### ISSUE TITLE
'io.airlift.drift' vs 'com.facebook.drift'

### ISSUE THREAD

**Issue by edudar** [airlift/drift#117]
This is rather a question than an issue. I see that `io.airlift.drift` versions stopped at `1.18` and then there is `com.facebook.drift` with its version starting at `1.19`. Is this the way new versions will be released going forward or is `com.facebook.drift` a fork of this lib with its own path?

**Comment by dain** [comment]
Facebook forked drift for some reason.  This is the official canonical repository.
