### ISSUE TITLE
why the request is requestTimeout，but it didn't throw exception

### ISSUE THREAD

**Issue by naah69** [airlift/drift#97]
i had set connectTimeout and requestTimeout in DriftNettyClientConfig.
```
driftNettyClientConfig.setConnectTimeout(new Duration(connectTimeout, TimeUnit.MILLISECONDS));
driftNettyClientConfig.setRequestTimeout(new Duration(requestTimeout, TimeUnit.MILLISECONDS));
```
but it  didn't work;

i use 1000 threads to pressure test for 1 minutes,it always like the below:
![image](https://user-images.githubusercontent.com/25682169/48237732-f23dbd00-e402-11e8-9eb4-f6305d430629.png)

and the result is like below:
![image](https://user-images.githubusercontent.com/25682169/48237787-4d6faf80-e403-11e8-81e0-185b9a12940c.png)

**Comment by dain** [comment]
My guess is your application had a long GC which can not be interrupted.  So it is likely the timer fired but the successful result was available, so the system returned that result.  Also, make sure you are using connection pooling, and I would recommend async APIs for anything high volume.
